IPL/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ipl_report.urls'))
]


urlpatterns.extend([
    *static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, settings.STATICFILES_DIRS[0])),
])

ipl_report/urls.py
from django.urls import path

from ipl_report import views

app_name = 'ipl_report'
urlpatterns = [
    path('report/', views.report, name='report'),
]

ipl_report/models.py
from django.db import models

# Create your models here.

ipl_report/forms.py
from django.forms import forms


# class ReportForm(forms.Form):
#     season = forms.

ipl_report/views.py
import pandas as pd
from django.shortcuts import render

deliveries = pd.read_csv('csv_files/deliveries.csv')
matches = pd.read_csv('csv_files/matches.csv')


def analyse(season):
    season_matches = matches.loc[matches['season'] == season]
    top_teams = list(season_matches.assign(
        win_count=season_matches.apply(
            lambda x: season_matches.winner.value_counts().to_dict()[x.team1], axis=1
        ))[['team1', 'win_count']].drop_duplicates().sort_values(
        'win_count', ascending=False)[:4]['team1'])
    toss_winner = list(season_matches.assign(
        toss_count=season_matches.apply(
            lambda x: season_matches.toss_winner.value_counts().to_dict()[x.team1], axis=1
        ))[['team1', 'toss_count']].drop_duplicates().sort_values(
        'toss_count', ascending=False)[:1]['team1'])
    player_of_match = list(season_matches.assign(
        player_of_match_count=season_matches.apply(
            lambda x: season_matches.player_of_match.value_counts().to_dict()[x.player_of_match], axis=1
        ))[['player_of_match', 'player_of_match_count']].drop_duplicates().sort_values(
        'player_of_match_count', ascending=False)[:1]['player_of_match'])
    top_team_list = season_matches[season_matches['winner'] == top_teams[0]]

    max_win_location = list(top_team_list.assign(
        venue_win_count=top_team_list.apply(
            lambda x: top_team_list.venue.value_counts().to_dict()[x.venue], axis=1
        ))[['venue', 'venue_win_count']].drop_duplicates().sort_values(
        'venue_win_count', ascending=False)[:1]['venue'])

    choose_to_bat_first = season_matches.loc[season_matches['toss_decision'] == 'bat']

    percent_of_team_decided_to_bat = len(choose_to_bat_first.index) / len(season_matches.index) * 100

    highest_margin_run_team = choose_to_bat_first.loc[choose_to_bat_first['win_by_runs'].idxmax()]['winner']

    team_won_by_highest_wickets = season_matches.loc[season_matches['win_by_wickets'].idxmax()]['winner']

    seasons = matches['season'].drop_duplicates()
    return {
        'top_teams': top_teams,
        'toss_winner': toss_winner[0],
        'player_of_match': player_of_match[0],
        'max_won_team': top_teams[0],
        'max_win_location': max_win_location[0],
        'percent_of_team_decided_to_bat': percent_of_team_decided_to_bat,
        'highest_margin_run_team': highest_margin_run_team,
        'team_won_by_highest_wickets': team_won_by_highest_wickets,
        'seasons': seasons
    }


def report(request):
    season = request.GET.get('season', '2017')
    context = analyse(int(season))
    context['season'] = season
    return render(request, template_name='report.html', context=context, )

templates/report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>IPL Reports {{ season }}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta name="title" content="IPL Reports {{ season }}" />
    <meta name="description" content="IPL Reports {{ season }}" />
</head>
<body>
<div class="jumbotron text-center">
    <h2>IPL Report - {{ season }}</h2>
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <p>Reports for the season selected!</p>
        </div>
        <div class="col-md-4">
            <form action="{% url 'ipl_report:report' %}" class="form-inline">
                <select id="" name="season" class="form-control">
                    {% for item in seasons %}<option value="{{ item }}">{{ item }}</option>{% endfor %}
                </select>
                <input type="submit" value="Submit" class="btn btn-sm btn-info" />
            </form>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <h2>Report for season {{ season }}</h2>
            <img src="/static/p1.png" class="img img-hover w-100" alt="cover">
        </div>
        <div class="col-sm-4"></div>
        <div class="col-sm-12">
            <h4>Top 4 teams in terms of wins</h4>
            <ol>
                {% for item in top_teams %}
                <li>{{ item }}</li>
                {% endfor %}
            </ol>
        </div>
        <hr class="bordered" />
        <div class="col-sm-12">
            <h4>{{ toss_winner }}</h4>
            <p>Team that won the most number of tosses in the season</p>
        </div>
        <hr />
        <div class="col-sm-12">
            <h4>{{ player_of_match }}</h4>
            <p>The player who won the maximum number of Player of the Match awards</p>
        </div>
        <hr />
        <div class="col-sm-12">
            <h4>{{ max_won_team }}</h4>
            <p>The team which won max matches in the whole season</p>
        </div>
        <hr />
        <div class="col-sm-12">
            <h4>{{ max_win_location }}</h4>
            <p>The location having the most number of wins for the top team</p>
        </div>
        <hr />
        <div class="col-sm-8">
            <img src="/static/p3.png" class="img img-hover w-100" alt="cover">
        </div>
        <div class="col-sm-4">
        </div>
        <hr />
        <div class="col-sm-12">
            <h4>{{ percent_of_team_decided_to_bat }}</h4>
            <p>Percentage of teams decided to bat when they won the toss</p>
        </div>
        <hr />
        <div class="col-sm-12">
            <h4>{{ highest_margin_run_team }}</h4>
            <p>The team won by the highest margin of runs  for the season</p>
        </div>
        <hr />
        <div class="col-sm-12">
            <h4>{{ team_won_by_highest_wickets }}</h4>
            <p>The team won by the highest number of wickets for the season</p>
        </div>
        <hr />
        <div class="col-sm-8">
            <img src="/static/p4.png" class="img img-hover w-100" alt="cover">
        </div>
        <div class="col-sm-4">
        </div>
    </div>
</div>
</body>
</html>